apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: my-learn-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: ReplicaSet
    name: my-learn-rs
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 90
