apiVersion: v1
kind: Service
metadata:
  name: learn-cluster
spec:
  selector:
    app: nginxserver
  ports:
    - name: learn-cluster-port
      protocol: TCP
      port: 8080
      targetPort: http-web-nginx
  type: ClusterIP
