apiVersion: v1
kind: Pod
metadata:
  name: "network-learn"
spec:
  containers:
    - name: c00
      image: ubuntu
      command:
        [
          "/bin/bash",
          "-c",
          "while true; do echo Hello Tuan dep trai cap network-learn; sleep 5 ; done",
        ]
    - name: httpd
      image: httpd
      ports:
        - containerPort: 80
