apiVersion: v1
kind: Pod
metadata:
  name: videthuong
  labels:
    app: videthuong
spec:
  containers:
    - name: c00
      image: 084823754304.dkr.ecr.us-east-1.amazonaws.com/perq-soleil-landing-page_prod:0.0.18
      imagePullPolicy: Always
      restartPolicy: Always
      ports:
        - containerPort: 3000
          protocol: TCP
          name: http
  imagePullSecrets:
    - name: regcred
